### PR TITLE
added vgroup to tblfns

### PR DESCRIPTION
**Pull request by SpacialTree**
Added `vgroup` to glob list of table filenames so merge catalogs merges the correct catalogs.

### CODE REVIEW

**Review by keflavich — CHANGES_REQUESTED** [review]
This isn't a necessary addition, is it?  All it will do is filter out files that do not have `vgroup` in the name, and those files simply shouldn't exist after running this version of the code.

**Comment by SpacialTree** [comment]
The previous version will not find the new catalog names as there is no wildcard in the old filename. 

`..visit{visitid:03d}_exp{exposure:05d}...`
versus 
`...visit{visitid:03d}_vgroup*_exp{exposure:05d}...`

The script without this update will only merge the old catalog files, and it will fail if only the current version has been run.

**Comment by keflavich** [comment]
ah, maybe it's better to just put a wildcard (`*`) instead of `_vgroup*`?

**Comment by SpacialTree** [comment]
`...visit{visitid:03d}*_exp{exposure:05d}...`

Like this?

**Pull request merged**
